# SMTP Configuration for Email Sending (Mailtrap)
smtp.host=sandbox.smtp.mailtrap.io
smtp.port=587
smtp.user=9709aa79773f69
smtp.pass=5a9ccc017adbbd
smtp.from=noreply@nkbookstore.com
mail.smtp.auth=true
mail.smtp.starttls.enable=true
