# SMTP Configuration for Email Sending
smtp.host=smtp.gmail.com
smtp.port=587
smtp.user=xuanbinhkhoi@gmail.com
smtp.pass=chay ywrs ubck wuab
smtp.from=xuanbinhkhoi@gmail.com
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.smtp.ssl.trust=smtp.gmail.com
